service: image_compressor
image: shved270189/image_compressor

servers:
  web:
    - 138.201.118.229

proxy:
  ssl: true
  hosts:
    - image.bondev.eu
    - www.image.bondev.eu
  app_port: 8000
  healthcheck:
    path: /api/health

registry:
  username: shved270189
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
